name: Latest book list from a goodreads

# Explicitly set permissions to minimum required
permissions:
  contents: write  # Needed to update README
  actions: read    # Needed to read workflow

# Prevent concurrent runs that could conflict
concurrency:
  group: goodreads-update
  cancel-in-progress: true
  
on:
  schedule: # Run workflow automatically
    # This will make it run every hour
    - cron: "0 * * * *"
    # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  workflow_dispatch:
jobs:
  update-readme-with-goodreads-books:
    name: Update this repo's README with what you're currently reading
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Prevent runaway processes
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          # Use a token with limited scope if possible
          token: ${{ github.token }}
          
      - name: Validate inputs
        run: |
          if [ -z "${{ secrets.GOODREADS_USER_ID }}" ]; then
            echo "Error: GOODREADS_USER_ID secret is not set"
            exit 1
          fi
          
      - name: Update Goodreads profile
        uses: lancefrench/goodreads-profile-workflow@a1b8b48b991987cb356422d51fcc91a81a2b6e26
        with:
          # Replace this with your goodreads user id
          goodreads_user_id: "${{ secrets.GOODREADS_USER_ID }}"
          shelf: "currently-reading"
